### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by panda2134** [panda2134/OICode#2]
Chapter 7:
- [ ] Uva 1354
- [ ] Learn eg7-9 UVa 1601
- [ ] UVa 140 
- [ ] UVa 11212
- [ ] UVa 1374 
- [ ] UVa 1602
- [ ] UVa 1603 

Chapter 9:
- [ ] Backpack http://www.cnblogs.com/jbelial/articles/2116074.html

Training:
- [ ] 7-5 UVa 690
- [ ] 7-7 UVa 12558
- [ ] 7-8 UVa 12107
- [ ] 7-9 UVa 1604
- [x] 7-13 UVa 817  //No Special Judge
- [ ] Learn 7-17 UVa 11694
- [ ] 7-18 UVa 10384
